/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Treino Smart
 * API de treino
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetPing200 = {
  message: string;
};

export type GetPing400 = {
  error: string;
  code: string;
};

export type GetPing401 = {
  error: string;
  code: string;
};

export type GetPing404 = {
  error: string;
  code: string;
};

export type GetPing500 = {
  error: string;
  code: string;
};

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId?: string;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  /** @nullable */
  sets: number | null;
  /** @nullable */
  reps: number | null;
  /** @nullable */
  restTimeInSeconds: number | null;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItemMetricType =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemExercisesItemMetricType)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemExercisesItemMetricType];

export const CreateWorkoutPlanBodyWorkoutDaysItemExercisesItemMetricType = {
  WEIGHT_REPS: "WEIGHT_REPS",
  REPS_ONLY: "REPS_ONLY",
  TIME: "TIME",
  DISTANCE_TIME: "DISTANCE_TIME",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  sets?: number | null;
  /** @nullable */
  reps?: number | null;
  /** @nullable */
  suggestedWeight?: number | null;
  metricType: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItemMetricType;
  /** @nullable */
  restTimeInSeconds?: number | null;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItemMetricType =
  (typeof CreateWorkoutPlan201WorkoutDaysItemExercisesItemMetricType)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemExercisesItemMetricType];

export const CreateWorkoutPlan201WorkoutDaysItemExercisesItemMetricType = {
  WEIGHT_REPS: "WEIGHT_REPS",
  REPS_ONLY: "REPS_ONLY",
  TIME: "TIME",
  DISTANCE_TIME: "DISTANCE_TIME",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  sets?: number | null;
  /** @nullable */
  reps?: number | null;
  /** @nullable */
  suggestedWeight?: number | null;
  metricType: CreateWorkoutPlan201WorkoutDaysItemExercisesItemMetricType;
  /** @nullable */
  restTimeInSeconds?: number | null;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @nullable */
  sets: number | null;
  /** @nullable */
  reps: number | null;
  /** @nullable */
  restTimeInSeconds: number | null;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutDay200ExercisesItem[];
  weekDay: GetWorkoutDay200WeekDay;
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type FinishWorkoutSessionBodyExercisesItemSetsItem = {
  order: number;
  weight?: number;
  reps?: number;
  durationInSeconds?: number;
  distanceInMeters?: number;
};

export type FinishWorkoutSessionBodyExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  exerciseId: string;
  restTimeInSeconds: number;
  sets: FinishWorkoutSessionBodyExercisesItemSetsItem[];
};

export type FinishWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt?: string;
  exercises: FinishWorkoutSessionBodyExercisesItem[];
};

export type FinishWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  completed: boolean;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type FinishWorkoutSession401 = {
  error: string;
  code: string;
};

export type FinishWorkoutSession404 = {
  error: string;
  code: string;
};

export type FinishWorkoutSession409 = {
  error: string;
  code: string;
};

export type FinishWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats404 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetMeTrainData200 = {
  userId: string;
  name: string;
  email: string;
  weightInGrams?: number;
  heightInCentimeters?: number;
  age?: number;
  bodyFatPercentage?: number;
} | null;

export type GetMeTrainData401 = {
  error: string;
  code: string;
};

export type GetMeTrainData500 = {
  error: string;
  code: string;
};

export type UpsertMeBody = {
  name: string;
};

export type UpsertMe200 = {
  userId: string;
  name: string;
};

export type UpsertMe401 = {
  error: string;
  code: string;
};

export type UpsertMe500 = {
  error: string;
  code: string;
};

export type GetMyMetrics200MetricsItem = {
  id: string;
  /** @minimum 0 */
  weightInGrams?: number;
  /** @minimum 0 */
  heightInCentimeters?: number;
  /** @minimum 0 */
  age?: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage?: number;
  createdAt: string;
};

export type GetMyMetrics200 = {
  metrics: GetMyMetrics200MetricsItem[];
};

export type GetMyMetrics401 = {
  error: string;
  code: string;
};

export type GetMyMetrics500 = {
  error: string;
  code: string;
};

export type UpsertBodyMetricBody = {
  weightInGrams?: number;
  heightInCentimeters?: number;
  age?: number;
  bodyFatPercentage?: number;
};

export type UpsertBodyMetric200 = {
  id: string;
  weightInGrams?: number;
  heightInCentimeters?: number;
  age?: number;
  bodyFatPercentage?: number;
  createdAt: string;
};

export type UpsertBodyMetric401 = {
  error: string;
  code: string;
};

export type UpsertBodyMetric500 = {
  error: string;
  code: string;
};

export type GetMyDiets200DietsItem = {
  id: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export type GetMyDiets200 = {
  diets: GetMyDiets200DietsItem[];
};

export type GetMyDiets401 = {
  error: string;
  code: string;
};

export type GetMyDiets500 = {
  error: string;
  code: string;
};

export type UpsertBodyDietBody = {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export type UpsertBodyDiet200 = {
  id: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  createdAt: string;
};

export type UpsertBodyDiet401 = {
  error: string;
  code: string;
};

export type UpsertBodyDiet500 = {
  error: string;
  code: string;
};

/**
 * Rota de teste
 */
export type getPingResponse200 = {
  data: GetPing200;
  status: 200;
};

export type getPingResponse400 = {
  data: GetPing400;
  status: 400;
};

export type getPingResponse401 = {
  data: GetPing401;
  status: 401;
};

export type getPingResponse404 = {
  data: GetPing404;
  status: 404;
};

export type getPingResponse500 = {
  data: GetPing500;
  status: 500;
};

export type getPingResponseSuccess = getPingResponse200 & {
  headers: Headers;
};
export type getPingResponseError = (
  | getPingResponse400
  | getPingResponse401
  | getPingResponse404
  | getPingResponse500
) & {
  headers: Headers;
};

export type getPingResponse = getPingResponseSuccess | getPingResponseError;

export const getGetPingUrl = () => {
  return `/ping/`;
};

export const getPing = async (
  options?: RequestInit,
): Promise<getPingResponse> => {
  return customFetch<getPingResponse>(getGetPingUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get workout plan details
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get workout day details
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Finish workout session
 */
export type finishWorkoutSessionResponse200 = {
  data: FinishWorkoutSession200;
  status: 200;
};

export type finishWorkoutSessionResponse401 = {
  data: FinishWorkoutSession401;
  status: 401;
};

export type finishWorkoutSessionResponse404 = {
  data: FinishWorkoutSession404;
  status: 404;
};

export type finishWorkoutSessionResponse409 = {
  data: FinishWorkoutSession409;
  status: 409;
};

export type finishWorkoutSessionResponse500 = {
  data: FinishWorkoutSession500;
  status: 500;
};

export type finishWorkoutSessionResponseSuccess =
  finishWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type finishWorkoutSessionResponseError = (
  | finishWorkoutSessionResponse401
  | finishWorkoutSessionResponse404
  | finishWorkoutSessionResponse409
  | finishWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type finishWorkoutSessionResponse =
  | finishWorkoutSessionResponseSuccess
  | finishWorkoutSessionResponseError;

export const getFinishWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}/finish`;
};

export const finishWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  finishWorkoutSessionBody: FinishWorkoutSessionBody,
  options?: RequestInit,
): Promise<finishWorkoutSessionResponse> => {
  return customFetch<finishWorkoutSessionResponse>(
    getFinishWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(finishWorkoutSessionBody),
    },
  );
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse404 = {
  data: GetStats404;
  status: 404;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse404
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Get user train data
 */
export type getMeTrainDataResponse200 = {
  data: GetMeTrainData200;
  status: 200;
};

export type getMeTrainDataResponse401 = {
  data: GetMeTrainData401;
  status: 401;
};

export type getMeTrainDataResponse500 = {
  data: GetMeTrainData500;
  status: 500;
};

export type getMeTrainDataResponseSuccess = getMeTrainDataResponse200 & {
  headers: Headers;
};
export type getMeTrainDataResponseError = (
  | getMeTrainDataResponse401
  | getMeTrainDataResponse500
) & {
  headers: Headers;
};

export type getMeTrainDataResponse =
  | getMeTrainDataResponseSuccess
  | getMeTrainDataResponseError;

export const getGetMeTrainDataUrl = () => {
  return `/me/`;
};

export const getMeTrainData = async (
  options?: RequestInit,
): Promise<getMeTrainDataResponse> => {
  return customFetch<getMeTrainDataResponse>(getGetMeTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert my train data
 */
export type upsertMeResponse200 = {
  data: UpsertMe200;
  status: 200;
};

export type upsertMeResponse401 = {
  data: UpsertMe401;
  status: 401;
};

export type upsertMeResponse500 = {
  data: UpsertMe500;
  status: 500;
};

export type upsertMeResponseSuccess = upsertMeResponse200 & {
  headers: Headers;
};
export type upsertMeResponseError = (
  | upsertMeResponse401
  | upsertMeResponse500
) & {
  headers: Headers;
};

export type upsertMeResponse = upsertMeResponseSuccess | upsertMeResponseError;

export const getUpsertMeUrl = () => {
  return `/me/`;
};

export const upsertMe = async (
  upsertMeBody: UpsertMeBody,
  options?: RequestInit,
): Promise<upsertMeResponse> => {
  return customFetch<upsertMeResponse>(getUpsertMeUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertMeBody),
  });
};

/**
 * @summary Get my body metrics history
 */
export type getMyMetricsResponse200 = {
  data: GetMyMetrics200;
  status: 200;
};

export type getMyMetricsResponse401 = {
  data: GetMyMetrics401;
  status: 401;
};

export type getMyMetricsResponse500 = {
  data: GetMyMetrics500;
  status: 500;
};

export type getMyMetricsResponseSuccess = getMyMetricsResponse200 & {
  headers: Headers;
};
export type getMyMetricsResponseError = (
  | getMyMetricsResponse401
  | getMyMetricsResponse500
) & {
  headers: Headers;
};

export type getMyMetricsResponse =
  | getMyMetricsResponseSuccess
  | getMyMetricsResponseError;

export const getGetMyMetricsUrl = () => {
  return `/me/metrics`;
};

export const getMyMetrics = async (
  options?: RequestInit,
): Promise<getMyMetricsResponse> => {
  return customFetch<getMyMetricsResponse>(getGetMyMetricsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create or get latest body metric
 */
export type upsertBodyMetricResponse200 = {
  data: UpsertBodyMetric200;
  status: 200;
};

export type upsertBodyMetricResponse401 = {
  data: UpsertBodyMetric401;
  status: 401;
};

export type upsertBodyMetricResponse500 = {
  data: UpsertBodyMetric500;
  status: 500;
};

export type upsertBodyMetricResponseSuccess = upsertBodyMetricResponse200 & {
  headers: Headers;
};
export type upsertBodyMetricResponseError = (
  | upsertBodyMetricResponse401
  | upsertBodyMetricResponse500
) & {
  headers: Headers;
};

export type upsertBodyMetricResponse =
  | upsertBodyMetricResponseSuccess
  | upsertBodyMetricResponseError;

export const getUpsertBodyMetricUrl = () => {
  return `/me/metrics`;
};

export const upsertBodyMetric = async (
  upsertBodyMetricBody: UpsertBodyMetricBody,
  options?: RequestInit,
): Promise<upsertBodyMetricResponse> => {
  return customFetch<upsertBodyMetricResponse>(getUpsertBodyMetricUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertBodyMetricBody),
  });
};

/**
 * @summary Get my body diets history
 */
export type getMyDietsResponse200 = {
  data: GetMyDiets200;
  status: 200;
};

export type getMyDietsResponse401 = {
  data: GetMyDiets401;
  status: 401;
};

export type getMyDietsResponse500 = {
  data: GetMyDiets500;
  status: 500;
};

export type getMyDietsResponseSuccess = getMyDietsResponse200 & {
  headers: Headers;
};
export type getMyDietsResponseError = (
  | getMyDietsResponse401
  | getMyDietsResponse500
) & {
  headers: Headers;
};

export type getMyDietsResponse =
  | getMyDietsResponseSuccess
  | getMyDietsResponseError;

export const getGetMyDietsUrl = () => {
  return `/me/diets`;
};

export const getMyDiets = async (
  options?: RequestInit,
): Promise<getMyDietsResponse> => {
  return customFetch<getMyDietsResponse>(getGetMyDietsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create or get latest body diet
 */
export type upsertBodyDietResponse200 = {
  data: UpsertBodyDiet200;
  status: 200;
};

export type upsertBodyDietResponse401 = {
  data: UpsertBodyDiet401;
  status: 401;
};

export type upsertBodyDietResponse500 = {
  data: UpsertBodyDiet500;
  status: 500;
};

export type upsertBodyDietResponseSuccess = upsertBodyDietResponse200 & {
  headers: Headers;
};
export type upsertBodyDietResponseError = (
  | upsertBodyDietResponse401
  | upsertBodyDietResponse500
) & {
  headers: Headers;
};

export type upsertBodyDietResponse =
  | upsertBodyDietResponseSuccess
  | upsertBodyDietResponseError;

export const getUpsertBodyDietUrl = () => {
  return `/me/diets`;
};

export const upsertBodyDiet = async (
  upsertBodyDietBody: UpsertBodyDietBody,
  options?: RequestInit,
): Promise<upsertBodyDietResponse> => {
  return customFetch<upsertBodyDietResponse>(getUpsertBodyDietUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertBodyDietBody),
  });
};
